#| require './lib/white_gold/version.rb'
#{ gemspec.name }#{ " - #{ gemspec.summary }" if gemspec.summary }
===

Ruby gem for building pure ruby graphical user interface.<br>
Uses [TGUI](https://tgui.eu/) & [SFML](https://www.sfml-dev.org/) as a backend.<br>
Dedicated to creating simple applications and learning programming.

#{ sample.call "Taste", "sample/readme/taste.rb" }
### Output:<br>
<img src="./.github/img/screen_1.PNG" width="30%">   <img src="./.github/img/screen_2.PNG" width="30%">



Check out [sample](https://github.com/lpogic/white_gold/tree/master/sample) for more.

Requirements
---
- Ruby >= 3.2.2
- Fiddle >= 1.1.1

Binaries for Windows and Linux are bundled with the gem.

Installation
---
1) From official
```
gem install #{ gemspec.name }
```
2) From source
```
git clone https://github.com/lpogic/white_gold
cd white_gold
gem build white_gold.gemspec
gem install white_gold-#{ WhiteGold::VERSION }.gem
```

#{ sample.call "Basic usage", "sample/readme/basic.rb" }
#{ sample.call "Advanced usage", "sample/readme/advanced.rb" }

Check out [documentation](https://github.com/lpogic/white_gold/tree/master/doc/wiki) for more info.

Status
---
A hobby project.

Authors
---
#{ gemspec.authors.zip(Array(gemspec.email)).map{ "- #{_1} (#{_2})" }.join("\n") }
